### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by jparrent**
I found some 09ip spectra that were in microns and so I converted them to Angstroms. I also removed a 1-line header from two other spectra.

### CODE REVIEW

**Comment by guillochon** [comment]
Would a WISeREP full rebuild nuke these changes?

**Comment by jparrent** [comment]
MM, yes. Would you like me to build a sn-spectrum-ignore list? This list
could sit outside that repo and I could write a script that, once WISeREP
rebuilds, parses the list and makes the corrections.

It's also possible that the bokeh plotting script could multiply by 10,000
if wavelengths are in the range of 0.5 to 3.0, say. I never see numbers
less than 10.0 in UV, optical observations (in Angstroms), but that is an
assumption, so...

Let me know either way and I can look to address.

**Comment by guillochon** [comment]
Yeah it would probably be best to have a spectrum ignore list, and then add any modified files to the `donations` folder in `sne-external-spectra`. That way we aren't modifying the files coming out of WISeREP.

**Comment by jparrent** [comment]
Cool, feel free to revert to the previous state for the Wiserep repo.
Tonight I will throw those modified files to the donations folder. Where
would you like the wiserep-spectrum-ignore.txt list to live? Same
sne-external-spectra/donations directory?

**Comment by guillochon** [comment]
It should live with the spider, since the spider needs to read it, no?

**Comment by jparrent** [comment]
Got it, I'll fix this and notify.

**Pull request merged**
