### PR TITLE
Updated files and REAMEs.

### PR DESCRIPTION
**Pull request by jparrent**
This PR is updating only one spectrum, but it is also to confirm that the update mode is working.

### CODE REVIEW

**Comment by guillochon** [comment]
Go ahead and merge when you want, I've given you write privileges to this fork.

**Comment by jparrent** [comment]
Ah right, I forgot. But now I do not see the button that allows me to do this.
screen shot 2016-07-22 at 12 57 10 am

**Comment by jparrent** [comment]
I think I also need privileges for issues on the supernovae repo. I can create them, but I cannot close or edit existing issues.

**Comment by guillochon** [comment]
Raised you to admin for this repo, you should be able to do anything with it now...

**Comment by jparrent** [comment]
Thanks! Done now.

**Pull request merged**
